from django.urls import path
from .views import *

app_name = 'imdb'

urlpatterns = [
    # path('', index, name='index'),
    path('', IndexView.as_view(), name='index'),
    path('actor/all/', ActorListView.as_view(), name='actor-list'),
    path('actor/<int:pk>/', ActorDetailView.as_view(), name='actor-detail'),
    path('filter/actor/all/', FilterActorListView.as_view(), name='filter-actor-list'),
    path('movie/all/', MovieListView.as_view(), name='movie-list'),
    path('filter/movie/all/', FilterMovieListView.as_view(), name='filter-movie-list'),
    path("movie/by-year/<int:year>/", MovieYearArchiveView.as_view(), name="movie-year-archive"),
    path('movie/<slug:slug>/', MovieDetailView.as_view(), name='movie-detail'),
    # path('movie/<int:pk>/', MovieDetailView.as_view(), name='movie-detail'),
    path('director/list/', DirectorListView.as_view(), name='director-list'),
    path('director/<int:pk>/', DirectorDetailView.as_view(), name='director-detail'),
    path('<int:pk>/add-comment/', add_new_comment, name='add_new_comment'),
    path('<int:pk>/add-comment2/', add_new_comment2, name='add_new_comment2'),
    path('<int:pk>/add-comment/', add_new_comment, name='add_new_comment'),
    path('<int:pk>/add-actor-comment/', add_actor_comment, name='add-actor-comment'),
    path('add/director/comment/<int:pk>/', add_director_comment, name='add-director-comment'),
    path('sign/out/', logout_view, name='user-sign-out'),
    path('auth/', login_view, name='login-view'),
    path('sign/in/', login_user, name='user-sign-in'),
    path('add/new_actor/', add_new_actor, name='add-new-actor'),
    path('create/actor/', create_actor_view, name='create-actor-view'),
    path('create/account/page/', CreateAccountView.as_view(), name='create-account-page'),
    path('create/new/account/', create_new_account, name='create-new-account'),
    path('update/watchlist/<int:pk>/', update_watchlist, name='update-watchlist'),
    path('user/movie/lists/', PersonalMovieListsView.as_view(), name='user-movie-lists'),
    path('add/personal/movie/list/', add_personal_movie_list, name='add-personal-movie-list'),
    path('add/movie/to/personal/movie_list/<int:pk>/', add_movie_to_personal_movie_list, name='add-movie-to-personal-movie-list'),
    path('remove/movie/from/personal/movie_list/<int:pk1>/<int:pk2>/', remove_movie_from_personal_movie_list, name='remove-movie-from-personal-movie-list'),
    path('search/', search, name='search'),
    path('set/user/rate/<int:pk>/', set_user_rate, name='set-user-rate'),
    path('user/profile/<int:pk>/', UserProfileView.as_view(), name='user-profile'),
    path('movie/by/genre/view/<int:pk>/', MovieByGenreView.as_view(), name='movie-by-genre-view'),
    path('movie/comment/update/<int:pk>/', MovieCommentUpdateView.as_view(), name='movie-comment-update-view'),
    path('movie/comment/delete/<int:pk>/', MovieCommentDeleteView.as_view(), name='movie-comment-delete-view'),
    path('show/message/view/', ShowMessageView.as_view(), name='show-message-view'),
    path('send/message/', send_message, name='send-message'),
    path('message/list/view/', MessageListView.as_view(), name='message-list-view'),
    path('message/detail_view/<int:pk>/', MessageDetailView.as_view(), name='message-detail-view'),
    path('reply/message/', reply_message, name='reply-message'),
    path('get/to/message/list', get_to_message_list, name='get-to-message-list'),
    path('api/director/list/', DirectorListAPIView.as_view(), name='api-director-list'),
    path('api/actor/list/', ActorListAPIView.as_view()),
    path('api/movie/list/', MovieListAPIView.as_view()),
    path('api/actor/<int:pk>/', ActorDetailAPIView.as_view()),
    path('api/director/update/<int:pk>/', DirectorUpdateAPIView.as_view()),
    path('api/create/movie/comment/', CreateMovieCommentAPIView.as_view()),
    path('api/create/movie/comment2/', CreateMovieCommentAPIView2.as_view()),
    path('api/destroy/movie/comment/<int:pk>/', DestroyMovieCommentAPIView.as_view()),
    path('api/message/list/', MessageListAPIView.as_view()),
    path('api/create/message/', CreateMessageAPIView.as_view()),
    path('api/update/message/<int:pk>/', UpdateMessageAPIView.as_view()),
    path('api/destroy/message/<int:pk>/', DestroyMessageAPIView.as_view()),
    path('api/personal/movie/list/', PersonalMovieListAPIView.as_view()),
    path('api/update/personal/movie/list/<int:pk>/', UpdatePersonalMovieListAPIView.as_view()),
    path('api/single/page/actor/list/', SinglePageActorsListAPIView.as_view()),
    path('api/single/page/movie/list/', SinglePageMovieListAPIView.as_view())
]