# Generated by Django 5.0.1 on 2024-12-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0002_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
