# Generated by Django 5.0.1 on 2024-12-20 09:23

import django.utils.timezone
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_actor_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster', models.ImageField(blank=True, upload_to='movie_posters')),
                ('rating', models.FloatField(default=5.0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('trailer', embed_video.fields.EmbedVideoField(blank=True)),
                ('plot', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('actors', models.ManyToManyField(blank=True, related_name='movies', to='imdb.actor')),
            ],
        ),
    ]
