# Generated by Django 5.0.1 on 2025-01-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_moviecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviecomment',
            options={'ordering': ['-created']},
        ),
    ]
