# Generated by Django 5.0.1 on 2025-01-07 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0007_alter_moviecomment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='imdb.actor')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
