# Generated by Django 5.0.1 on 2025-01-18 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0009_movie_users_to_watch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='user_actors',
            field=models.ManyToManyField(blank=True, related_name='favourite_actors', to=settings.AUTH_USER_MODEL),
        ),
    ]
