# Generated by Django 5.0.1 on 2025-01-18 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0010_actor_user_actors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='user_directors',
            field=models.ManyToManyField(blank=True, related_name='favourite_directors', to=settings.AUTH_USER_MODEL),
        ),
    ]
