# Generated by Django 5.0.1 on 2025-01-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0011_director_user_directors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='user_actors',
            new_name='actors_by_user',
        ),
    ]
