# Generated by Django 5.0.1 on 2025-01-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0012_rename_user_actors_actor_actors_by_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='user_directors',
            new_name='directors_by_user',
        ),
    ]
