# Generated by Django 5.0.1 on 2025-02-11 09:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0016_usermovierating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user_rated_this_movie',
            field=models.ManyToManyField(through='imdb.UserMovieRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
