# Generated by Django 5.0.1 on 2025-02-11 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0017_movie_user_rated_this_movie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_rated_this_movie',
            field=models.ManyToManyField(related_name='movies_rated_this_user', through='imdb.UserMovieRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
