# Generated by Django 5.0.1 on 2025-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0019_genre_alter_usermovierating_options_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
